### ISSUE TITLE
set @PropertyResource to fix file for all classes

### ISSUE THREAD

**Issue by mueller-jens** [xlate/property-inject#37]
@MikeEdgar  Is it possible to configure you library so that i can set the property files name to a fix file name for all @Property annotations? If not it will be a great featrue in my eyes.

**Comment by MikeEdgar** [comment]
Hi @mueller-jens - this sounds like a good idea, perhaps with a default. Are you thinking something similar to `application.properties`?

**Comment by mueller-jens** [comment]
@MikeEdgar Yes something like that. But in best case it should be configurable by an array of files which can ba additional loaded like for testing, local environment, and other statges

**Comment by mueller-jens** [comment]
Implemented with https://github.com/xlate/property-inject/pull/117
